# Generated by Django 3.0.9 on 2021-12-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniredpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageOfSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_own_staff', models.SmallIntegerField(default=90)),
                ('from_user', models.SmallIntegerField(default=70)),
            ],
        ),
        migrations.AddField(
            model_name='payforbalance',
            name='card_mask',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
