# Generated by Django 3.0.9 on 2021-12-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniredpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payforbalance',
            name='card_mask',
        ),
    ]
