# Generated by Django 3.0.9 on 2021-12-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankcourse',
            name='tashkil_value',
        ),
        migrations.AddField(
            model_name='rankcourse',
            name='content_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rankcourse',
            name='video_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='wallet_expire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='wallet_expire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='wallet_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
